name: First_test
on: push
jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome Test1
          run: echo "My First Github Action Job"

        - name: Listr Files
          run: ls

        - name: Read File
          run: cat README.md
          
